### ISSUE TITLE
Apple - 400 Bad Request on calling userFromToken Method

### ISSUE THREAD

**Issue by sandeepthakkar23** [SocialiteProviders/Providers#1004]
Hello,

I am using "laravel/socialite": "^5.6",  socialite for apple provider.

And I have implemented socialite as per this reference (https://devpeel.com/implement-apple-sign-in-with-laravel/) to Laravel 10.

After getting apple login response, passing required parameter to reference code. There is one method userFromToken which not working and giving below errors:

GuzzleHttp\Exception\ClientException: Client error: `POST https://appleid.apple.com/auth/token` resulted in a `400 Bad Request` response:
{&quot;error&quot;:&quot;invalid_request&quot;}

invalid_request

*The same things is working to postman request.

Please help for the same.

Thanks in advance!!

**Comment by hamrak** [comment]
https://developer.apple.com/documentation/technotes/tn3107-resolving-sign-in-with-apple-response-errors

Maybe it will help you solve or at least find your problem.

**Comment by sandeepthakkar23** [comment]
> https://developer.apple.com/documentation/technotes/tn3107-resolving-sign-in-with-apple-response-errors
> 
> Maybe it will help you solve or at least find your problem.

Thanks for answer. But I have checked same things using postman where is working fine.

**Comment by hamrak** [comment]
It's strange that you can't do it through the app (get error), but you can through Postman. 

It works for me, but I always generate a new JWT immediately upon request to be sure that it is valid.
That's why I sent a PR #1016 with extended configuration, so that I could use the certificate instead of the secret key.
Secret key is always generated.

Which HTTP Client do you have? Maybe is something wrong in the POST request if your secret key (token) is correct.

Here is good discussion: https://developer.apple.com/forums/thread/124521

**Comment by ian-nisbet** [comment]
I had the 400 invalid_request error, because I did not have the callback route defined for POST HTTP method. Other Socialite providers redirect to the defined URI, but Apple ID posts to APPLE_REDIRECT_URI
