### ISSUE TITLE
Laravel 5.5 question

### ISSUE THREAD

**Issue by codeitlikemiley** [SocialiteProviders/Providers#124]
I see in the docs that you, you may need to remove 
 Laravel\Socialite\SocialiteServiceProvider

but by default in laravel 5.5

the socialiteserviceprodiver is being loaded...

how can i disabled it then?

**Comment by codeitlikemiley** [comment]
How do use it on laravel 5.5 anyway... can someone shed some light

**Comment by Axieum** [comment]
I'm going to assume you've already tried following the documentation for adding a new service; http://socialiteproviders.github.io/providers/twitter/. This is basically everything you have to do; except removing the `Laravel\Socialite\SocialiteServiceProvider` since Laravel automatically "discovers" this package. I recommend you still install `Laravel\Socialite` as this gives you access to the `Socialite::` facade.

----------------

This is how I set mine up - I'd show you my repository but it's private (sorry):

When you `composer require `laravel/socialite`, Laravel automatically detects this package and hence you do not need to manually set things up. However, when you install Socialite Providers you'll need to do the basic setup.

In your `config\app.php` simply add the following line under the `providers` array:
```php
SocialiteProviders\Manager\ServiceProvider::class,
```

Then, locate your Event Service Provider class under `app\Providers\EventServiceProvider.php`. Add the following array to the `$listen` array - this will be where you register all the events:
```php
'SocialiteProviders\Manager\SocialiteWasCalled' => [
    // 'SocialiteProviders\Twitter\TwitterExtendSocialite@handle',
    // Simply just add more services here.
]
```

In order to make OAuth requests, you'll need to provide your key/id and secret alongside the request. Luckily, Socialite does this for you, all you need to do is put your keys in your `.env` file, or reference them in your `config\services.php` file.

```php
// You only need to add this to your `config/services.php` file should you NOT put it in your `.env`.
// Just replace `env('TWITTER_KEY')` with your key; just be careful when pushing this to VC. 
'twitter' => [
    'client_id' => env('TWITTER_KEY'),
    'client_secret' => env('TWITTER_SECRET'),
    'redirect' => env('TWITTER_REDIRECT_URI'),
],
```

Note: most services require you to whitelist valid redirect URIs for security (only your domains can be redirected to); this redirect URI is basically the route to your callback function.

IF you installed Laravel's Socialite, then you can start making requests with `Socialite::`.

In your controller (or wherever), have a function that makes the request and redirects them:
```php
return Socialite::with('twitter')->redirect();
```

Then, you'll need to setup a route to handle the callback:
```php
// Retrieve the response.
$response = Socialite::driver('twitter')->user();
// dd($response); // uncomment this line to see the json response obtained.
```

**Comment by codeitlikemiley** [comment]
just to update this tread, since laravel auto package discovery is at work we dont need to add the serviceprovider on the config/app.php...

we only need to add of course the listener for the event for specific provider
