### ISSUE TITLE
Snapchat Provider - Missing PKCE Parameters

### ISSUE THREAD

**Issue by alex0082ass** [SocialiteProviders/Providers#260]
Hi,

What can be the cause of the following error?

`return Socialite::with('snapchat')->redirect();`

`{"error":"invalid_request","error_description":"Missing PKCE parameters."}`

Thanks

**Comment by dwightwatson** [comment]
Did you happen to resolve this issue, and if so how?

**Comment by trbsi** [comment]
Socialite plugin for Snapchat is working fine. The problem why people get that stupid "Missing PKCE Parameters " error is because you need to do some extra steps:
1. Take your client ID and client secret from:
![snapchat_client_id](https://user-images.githubusercontent.com/3958715/157739035-716c7751-5a15-44fe-994e-9b460c852e13.png)

2. Add your accounts as Demo Users
![snapchat_users](https://user-images.githubusercontent.com/3958715/157739160-991f6814-411c-459e-905b-977fcd1c9e0a.png)

3. Add correct redirect urls
![Screenshot_2](https://user-images.githubusercontent.com/3958715/157739314-8062cb32-021f-4dea-8263-f0db11de91c2.png)
 

That's it, it should work fine.
