### ISSUE TITLE
Driver [Twitch] not supported. 

### ISSUE THREAD

**Issue by mohammed-elattar** [SocialiteProviders/Providers#286]
### #twitch Provider
**Laravel 5.7
PHP 7.2**
**Driver [Twitch] not supported issue** , i spent the whole day trying to fix it without luck 
I folllowed the instructions and always getting the same error , 
I tried all solutions from all issues mentioned here with out luck
I tried capital and small letter for twitch word inside with function  
return Socialite::with('twitch')->redirect();::with("Twitch")

and here is the **Event Service provider file**
protected $listen = [
        Registered::class => [
            SendEmailVerificationNotification::class,
          \SocialiteProviders\Manager\SocialiteWasCalled::class => [
            'SocialiteProviders\\Twitch\\TwitchExtendSocialite@handle',
          ],
        ],
    ];

and  **config\app.php**

App\Providers\RouteServiceProvider::class,
\SocialiteProviders\Manager\ServiceProvider::class

and **aliases**
'Socialite' => Laravel\Socialite\Facades\Socialite::class,
any help please

**Comment by maengija** [comment]
Had a same problem. Try write Twitch in lower case.

**Comment by oranges13** [comment]
@ghost #282 fixed this for me. I was lacking a slash in front of `SocialiteProviders\Manager\SocialiteWasCalled::class'

@mohammed-elattar your issue is that your `\SocialiteProviders\Manager\SocialiteWasCalled::class' array is INSIDE your `Registered::class` array which is incorrect.

It should look like this
```
protected $listen = [
    Registered::class => [
        SendEmailVerificationNotification::class,
   ],

    \SocialiteProviders\Manager\SocialiteWasCalled::class => [
        'SocialiteProviders\Twitch\TwitchExtendSocialite@handle',
    ],
];
```

You may also need to add slashes in your `'SocialiteProviders\\Twitch\\TwitchExtendSocialite@handle',`

**Comment by K1lleR8** [comment]
My code looks like as it should be but I still get the same error!

I'd appreciate any help.

**Comment by atymic** [comment]
@K1lleR8 can you send your raw config? :)
