### ISSUE TITLE
Help with JIRA provider

### ISSUE THREAD

**Issue by gmask** [SocialiteProviders/Providers#49]
Hey there, if this is the wrong place for this kind of post please direct me to the proper one.

I'm attempting to use the JIRA Socialite provider and cannot get it to work.

I have generated the `jira.pem` and `jira.pub` keys and they seem to be loaded fine, I've also added the application link to my JIRA instance and ensured the `jira.pub` key is pasted in the "Incoming Authentication" section. Still nothing works: attempting `Socialite::with('jira')->redirect();` returns:

> Received HTTP status code [401] with message "oauth_problem=consumer_key_unknown" when getting temporary credentials.

How do I properly use this provider? JIRA seems different from most of the other providers in the way the generic app is granted access, and that difference is not documented in the stub documentation of this particular provider.

My `config/services.php` block:

```
'jira' => [
        'client_id' => env('JIRA_KEY'),
        'client_secret' => env('JIRA_SECRET'),
        'redirect' => env('JIRA_REDIRECT_URI'),
        'base_uri' => env('JIRA_BASE_URI'),
    ],
```

My `.env` settings:

```
JIRA_KEY="test123"
JIRA_SECRET='test123'
JIRA_REDIRECT_URI=http://laravel.dev/login
JIRA_BASE_URI=http://atlassian.dev:8090
```

Does anyone use this provider that can give some guidance?

**Comment by faustbrian** [comment]
@gmask Has the issue been solved or does it still exist?

**Comment by gmask** [comment]
Yeah I never did get this working, and never heard from anyone who did, so I stopped trying to use Socialite in that project. It would be a lot nicer to have this provider though.

**Comment by faustbrian** [comment]
If you can provide me with test credentials and certificates I can take a look as I am not using JIRA.

**Comment by gmask** [comment]
Unfortunately our JIRA instance is hosted internally and I can't spin up a test instance on our site at the moment.

**Comment by christidis** [comment]
Using JIRA provider with SocialiteProviders is not clear to me either.
My understanding is that JIRA, on its own, cannot act as an Identity Provider. However, Atlassian offers a software called Crowd which can act as an Identity Provider instead. With Croud integrated to Jira, accounts could be synced from JIRA to Crowd and then any registered application could use Jira/Crowd as an IdP.

Having said that, it is not clear to me how to register `client_id`, `client_secret` and `redirect` url in Jira in order to use them in SocialiteProviders configuration and proceed with the [documentation](https://github.com/SocialiteProviders/Providers/tree/master/src/Jira).
```
'jira' => [    
  'client_id' => env('JIRA_CLIENT_ID'),  
  'client_secret' => env('JIRA_CLIENT_SECRET'),  
  'redirect' => env('JIRA_REDIRECT_URI') 
],
```

If you can provide more information that would be helpful.
