### ISSUE TITLE
ERROR: Flickr throws "Call to undefined method GuzzleHttp\Psr7\Response::send()"

### ISSUE THREAD

**Issue by tyler36** [SocialiteProviders/Providers#61]
After the authentication screen, on the callback when I try to run:
```
Socialite::driver('flickr')->user()
```

I get the following error:

```
FatalThrowableError in Server.php line 107:
Call to undefined method GuzzleHttp\Psr7\Response::send()
```

**Comment by faustbrian** [comment]
As you already have an installation running please figure out the issue and send a PR to fix it since you are a developer too. We simply don't have the time to fix all the issues that come up on our own since we don't use most of these providers on our own and they are written by 3rd-Party Developers.
