### ISSUE TITLE
PKCE support

### ISSUE THREAD

**Issue by robiiinos** [SocialiteProviders/Providers#686]
Hello there,

With the addition of PKCE on Laravel Socialite 5.x, I am wondering if any the current architecture of the provider are allowing support of PKCE.
For reference on how it can be enabled:
- https://github.com/laravel/socialite/pull/518
- https://github.com/laravel/socialite/pull/523

Thank you for your time ~

**Comment by atymic** [comment]
We now inherit the google provider directly ([see here](https://github.com/SocialiteProviders/Providers/blob/master/src/Google/Provider.php)) so if you are using socialite 5 and this package, then you are able to use PKCE.

It should be fairly easy to add to other providers as well if required since we extend the base class (though, you'll need to force socialite v5 in the composer json).
