### ISSUE TITLE
Discord Provider using Invalid Separator

### ISSUE THREAD

**Issue by mmsheeks** [SocialiteProviders/Providers#771]
The Discord provider made available through this collection seems to be outputting an invalid redirect URI, and I'm not sure why.

Discord expects a " " separator (url encoded, of course, to `%20`), but the resulting URL uses "+" to separate scopes. I double checked and the Discord Provider class specifies spaces for separators, but that's not the result I'm seeing when calling it. My code is below, in case that's helpful.
 
 ```php
 # /app/Http/Controllers/AuthController.php
 <?php

namespace App\Http\Controllers;

use Laravel\Socialite\Facades\Socialite;
use App\Http\Controllers\Controller;

class AuthController extends Controller
{
    public function redirect() {
        return Socialite::driver( 'discord' )
        ->scopes([ 'identify', 'email', 'guilds', 'guilds.join'] )
        ->redirect();
    }
...
```

generates the following URL (identifying information replaced with X)
`https://discord.com/oauth2/authorize?client_id=XXXXXX&redirect_uri=https%3A%2F%2FXXXX%2Foauth%2Fredirect%2F&scope=email+identify+guilds+guilds.join&response_type=code&state=XXXXX`

Any idea why this might be happening?

**Comment by thinkverse** [comment]
I'm a little confused as to what the issue is. The title says **GitHub Provider**, then the first paragraph says that the Discord provider outputs an invalid redirect URI, But right after that mentions how the scope separator encodes the separator incorrectly? Some clarification on what the issue is about would be nice. 🙂

But yes it does look like the Discord provider is using the wrong encoding type, it is using the default `PHP_QUERY_RFC1738` which encodes spaces with `+` as per the [documentation](https://www.php.net/http_build_query) for `http_build_query`. It technically should be using the `PHP_QUERY_RFC3986` encoding, which uses URL encoded spaces.

It is also clear after testing that Discord isn't enforcing that even though it's said to use it on their [documentation](https://discord.com/developers/docs/topics/oauth2#authorization-code-grant-authorization-url-example) and the OAuth 2.0 [RFC](https://datatracker.ietf.org/doc/html/rfc6749#section-3.3) their implementation follows. URL encoding using a `+` separator still applies the correct scopes to the authorization request so their decoding catches that incorrect encoding anyways.

It's an easy PR to submit, changing the encoding type. But as the current encoding works, I'll leave that decision up to @atymic and the core team. 🤷‍♂️

Hope that clears it up as to why it uses `+` as a separator and not a space.

**Comment by mmsheeks** [comment]
@thinkverse Sorry for the miscommunication on my part, posted that after a relatively long day and my brain was fried.

What I was specifically running into is that the **Discord Provider** was generating URLs that Discord was not accepting. When I send a request to Discord using the `PHP_QUERY_RFC1738` encoding, Discord's OAuth endpoint gives me an invalid URL error.

In any case, appreciate the clarification and you taking the time to look into it. I've circumnavigated the issue by just building my own Discord Provider class.

**Comment by thinkverse** [comment]
> What I was specifically running into is that the **Discord Provider** was generating URLs that Discord was not accepting. When I send a request to Discord using the `PHP_QUERY_RFC1738` encoding, Discord's OAuth endpoint gives me an invalid URL error.

What happens if you run the same scenario now with the original Discord provider? During testing, I couldn't get the invalid URL error to trigger, though it could have to do with limited scopes or a specific scope selection I didn't try.
