### ISSUE TITLE
Discord Package Needs PKCE Enabled

### ISSUE THREAD

**Issue by ferrari308guy** [SocialiteProviders/Providers#835]
While trying to retrieve the user information using the Laravel Socialite Discord package, I receive the following error:

> Client error: `POST https://discord.com/api/oauth2/token` resulted in a `400 Bad Request` response: {"error": "invalid_request", "error_description": "Missing \"code_verifier\""}

I tracked this issue down to the fact that this package needs to have PCKE enabled so that the `code_verifier` is passed along with the request for user information.

The fix is a one-line change in [this file](https://github.com/SocialiteProviders/Discord/blob/master/Provider.php). The following definition needs to be added:

> /**
     * Indicates if PKCE should be used.
     *
     * @var bool
     */
    protected $usesPKCE = true;

I saw that repo is marked as Read-Only, so I'm posting here because I'm not sure what the PR process is to get that fixed.

**Comment by atymic** [comment]
Just PR against this repo to the discord folder :)

**Comment by ferrari308guy** [comment]
Thanks. [Here's](https://github.com/SocialiteProviders/Providers/pull/836) the PR.

**Comment by greatsaltlake** [comment]
For what it's worth, I was getting the same response back from Discord which led me to believe PCKE being disabled was the issue. After a bit more debugging, it turned out I had a couple of config errors. My client secret was empty due to using the wrong ENV name, and my session domain was wrong due to using ngrok for local testing, so none of the session values were getting set. So if you're getting this error it's possible you have a different issue.

**Comment by ferrari308guy** [comment]
I looked into this and I also had a problem with the client secret ENV variable not being configured properly. After fixing that issue, this works without PKCE being enabled. I'll close the PR since it's not needed.
