### ISSUE TITLE
[Saml2] now throws "LightSamlValidationException: AudienceRestriction MUST BE a wellformed uri"

### ISSUE THREAD

**Issue by stevebauman** [SocialiteProviders/Providers#990]
Hi there,

Our SAML2 implementation was working fine, but after updating from `v4.5.0` to `v4.6.0` or `v4.7.0`, we receive the below exception:

```
LightSaml\Error\LightSamlValidationException
AudienceRestriction MUST BE a wellformed uri
```

https://flareapp.io/share/B5ZNRNv5#F53

https://github.com/SocialiteProviders/Saml2/releases/tag/4.6.0

This is due to the addition of some assertions here:

https://github.com/SocialiteProviders/Saml2/commit/988ca4470a3ab1892f7f0484310d44b23c0d10fd

How do we opt out of these? Or what is needed to pass these assertions? Our SAML2 authentication was working properly, so I have no idea where to start.

All of these validation changes should have been in a new major version (`v5.0.0`), as these will likely break most installations.

Downgrading to `v4.5.0` for now.

**Comment by stevebauman** [comment]
Hi @27pchrisl, thanks for the reply!

This SAML2 Socialite provider is setup with a Microsoft Azure.

> Does Flare have the contents of the AudienceRestriction $item variable?

Yes, here it is:

![Screenshot 2023-03-10 at 1 48 09 PM](https://user-images.githubusercontent.com/6421846/224400314-70dcc48f-5e94-4566-bf0a-89d520a3605b.png)

Do you see any issues with this? Let me know if you need more detail expanded 👍

**Comment by 27pchrisl** [comment]
Hi @stevebauman,

I see in https://flareapp.io/share/B5ZNRNv5#F44 you are setting `sp_entityid` to "patientprism.com". The EntityID should be a globally unique, opaque value formatted as a URI. Using something like "http://patientprism.com/saml" would be good. (Note that this is a simple string value, it doesn't represent a real URL.)

Ideally, the Saml2 Provider would catch this and throw a `ConfigurationException`, but also Azure should have rejected this value! Azure is reflecting that value back into the `Audience` element, despite it being incorrectly formed (https://learn.microsoft.com/en-us/azure/active-directory/develop/single-sign-on-saml-protocol#audience).

The fix is to change that value in the Provider configuration, and simultaneously change it at the Azure side (or, request Azure refresh your SP configuration from metadata if you're using that).

**Comment by stevebauman** [comment]
Thanks @27pchrisl! Really appreciate your time and help on this.

I'll give this a shot and try to have this deployed Monday for testing. I'll comment back and close this issue once confirmed 👍

**Comment by stevebauman** [comment]
This worked, thank you so much @27pchrisl! 🙏
